# Generated by Django 3.2.9 on 2021-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Quoted', 'Quoted'), ('Bound', 'Bound'), ('Accepted', 'Accepted'), ('Active', 'Active')], max_length=10),
        ),
    ]
