# Generated by Django 3.2.9 on 2021-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_policy_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('bound', 'Bound'), ('accepted', 'Accepted'), ('active', 'Active')], max_length=10),
        ),
    ]
