# Generated by Django 3.2.9 on 2021-11-25 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_alter_policy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='type',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
